### ISSUE TITLE
500 error while searching

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1607]
**How to reproduce:**
Search as:
`{"checkInDate":"2023-01-12T00:00:00Z","checkOutDate":"2023-01-14T00:00:00Z","roomDetails":[{"adultsNumber":1,"childrenNumber":0}],"nationality":"RU","residency":"RU","htIds":["Country_3748"]}` - Japan

**Expected result:**
- no error, search done well

**Actual result:**
- GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/9c253b68-a036-405c-bacb-4a63c714a369?top=10&skip=0 returns 500 error

```
An unhandled exception has occurred while executing the request.Exception: 
System.ArgumentException: Deadline date '1/1/0001 12:00:00 AM +00:00' is invalid (Parameter 'Date')
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.DeadlinePolicyProcessor.Process(Deadline deadline, DateTimeOffset checkInDate, CancellationPolicyProcessSettings cancellationPolicyProcessSettings) in /src/Api/Services/Accommodations/Availability/DeadlinePolicyProcessor.cs:line 18
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.RoomContractSetPolicyProcessor.Process(RoomContractSet roomContractSet, DateTimeOffset checkInDate, CancellationPolicyProcessSettings cancellationPolicyProcessSettings) in /src/Api/Services/Accommodations/Availability/RoomContractSetPolicyProcessor.cs:line 22
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.RoomContractSetPolicyProcessor.Process(List`1 roomContractSet, DateTimeOffset checkInDate, CancellationPolicyProcessSettings cancellationPolicyProcessSettings) in /src/Api/Services/Accommodations/Availability/RoomContractSetPolicyProcessor.cs:line 13
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.Steps.WideAvailabilitySearch.WideAvailabilityPolicyProcessor.<>c__DisplayClass0_0.<Process>b__0(AccommodationAvailabilityResult r) in /src/Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilityPolicyProcessor.cs:line 12
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.Steps.WideAvailabilitySearch.WideAvailabilityPolicyProcessor.Process(List`1 results, CancellationPolicyProcessSettings settings) in /src/Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilityPolicyProcessor.cs:line 11
   at CSharpFunctionalExtensions.ResultExtensions.Map[T,K,E](Result`2 result, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsLeftOperand.Map[T,K,E](Task`1 resultTask, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Map[T,K,E](Task`1 resultTask, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Map[T,K,E](Task`1 resultTask, Func`2 func)
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Map[T,K,E](Task`1 resultTask, Func`2 func)
   at HappyTravel.Edo.Api.Services.Accommodations.Availability.Steps.WideAvailabilitySearch.WideAvailabilitySearchService.GetResult(Guid searchId, AvailabilitySearchFilter filter, String languageCode) in /src/Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchService.cs:line 189
   at HappyTravel.Edo.Api.Controllers.AgentControllers.AvailabilitiesController.GetAvailabilitySearchResult(Guid searchId, AvailabilitySearchFilter options) in /src/Api/Controllers/AgentControllers/AvailabilitiesController.cs:line 90
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at HappyTravel.Edo.Api.Infrastructure.Middlewares.AgentRequestLoggingMiddleware.InvokeAsync(HttpContext context, IAgentContextInternal agentContextService) in /src/Api/Infrastructure/Middlewares/AgentRequestLoggingMiddleware.cs:line 39
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 249
   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 249
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by AlexeyShok** [comment]
@sergeyf-QA Is this issue still relevant? I checked and found no errors when searching with all suppliers included.

**Comment by nikolaeva31** [comment]
Error is repeated for steps (corrected in the description).

**Comment by ViTsvetkova** [comment]
@wnlstk please recheck this bug

**Comment by wnlstk** [comment]
this bug can't reproduce
