### ISSUE TITLE
Error while logging from the HotelBeds connector

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#545]
For example, `searchId - 'd51cbd99-81b7-4564-8652-8635eaa453d8'
`
```
An error occurred while writing to logger(s). (Exception of type 'System.OutOfMemoryException' was thrown.)Exception: 
System.AggregateException: An error occurred while writing to logger(s). (Exception of type 'System.OutOfMemoryException' was thrown.)
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
```

**Comment by mingazhev** [comment]
@DFSko could you please check?
I suspect the logger, may be error will be gone after update.
Step to reproduce is searching something in Dubai

**Comment by mingazhev** [comment]
@DFSko can we repeat this locally, running in docker?
Can we somehow handle this to use less memory?
Need to investigate
